### ISSUE TITLE
Funktion erweitern für "verschachtelte Seiten"

### ISSUE THREAD

**Issue by lck-git** [TN03/expandcontract#10]
Siehe https://cmsimpleforum.com/viewtopic.php?f=16&t=18315&p=83396#p83398

**Comment by TN03** [comment]
Basisfunktion sollte seit hier https://github.com/TN03/expandcontract/commit/be176a547d6939039e7620cdf245ab107fdd8e08 gegeben sein.
Allerdings wird es aufwändig, wenn übergeordnete Instanzen bei der Suche und / oder der Direktverlinkung geöffnet werden sollen. Ich frage mich, ob da Aufwnad / Nutzen noch halbwegs im Verhältnis steht?

**Comment by TN03** [comment]
> Basisfunktion sollte seit hier [be176a5](https://github.com/TN03/expandcontract/commit/be176a547d6939039e7620cdf245ab107fdd8e08) gegeben sein.

Da war ich wohl zu optimistisch: bei obigen Stand gibt es scheinbar eine Endlosschleife mit nachfolgendem Fehler wegen Speichermangel, wenn man mehrere Instanzen ineinander verschachtelt.

Weiß jemand warum?

**Comment by frase-git** [comment]
> Weiß jemand warum?

Weil wir einfach zu viel wollen ;-)
Ich wäre dafür, keine Verschachtelungen zuzulassen. Dafür gibt es andere Plugins.
Und ganz privat gefallen mir Accordions innerhalb von Accordions überhaupt nicht. Das wirkt auf mich wie "blinkender Text".

**Comment by TN03** [comment]
Und was ist eigentlich mit JS und CSS, bei Verschachtelungen?
Das würde dann wohl wieder doppelt eingefügt werden? Hier bleibt vermutlich nur, die Auswertung des PluginCalls auch innerhalb der Instanz zu erledigen?

**Comment by TN03** [comment]
> > Weiß jemand warum?
> 
> Weil wir einfach zu viel wollen ;-) Ich wäre dafür, keine Verschachtelungen zuzulassen. Dafür gibt es andere Plugins. Und ganz privat gefallen mir Accordions innerhalb von Accordions überhaupt nicht. Das wirkt auf mich wie "blinkender Text".

Gut, ich brauch das auch nicht :). Aber, wie soll man es verhindern?
Seiteninhalt vor Ausführung der Plugin-Aufrufe durchsuchen und wenn Expandcontract - Plugin dabei ist, Fehler werfen?
@olape-git: da kannst du mir doch sicher eine passende RegExp liefern die neuen und alten Plugin-Call entsprechend auswertet ;-).
Wenn ich mir im Core evaluate_cmsimple_scripting() bzw. evaluate_plugincall() anschaue, dann wird mir schwindelig.
Aber abgefangen werden muss es. Sonst schmiert die Seite ab.

**Comment by frase-git** [comment]
> Aber abgefangen werden muss es. Sonst schmiert die Seite ab.

Kannst du nochmal beschreiben, wann das passiert?

**Comment by lck-git** [comment]
> > Aber abgefangen werden muss es. Sonst schmiert die Seite ab.
> 
> Kannst du nochmal beschreiben, wann das passiert?

Beispiel: Erstelle unter "Verborgene Seite 1" Unterseiten und setze den Pluginaufruf in "Verborgene Seite 1" {{{expand}}}

![acc_verschachtelte Seiten](https://user-images.githubusercontent.com/22255655/159706886-7f3a4c43-334d-4484-9ec5-ac43f7be46bd.gif)

Ergebnis: weiße Seite mit Meldung:

> Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in D:\xampp\...\...\cmsimple\functions.php(242) : eval()'d code on line 1

**Comment by frase-git** [comment]
Ah, ja, klar.
Danke Ludwig.

**Comment by lck-git** [comment]
Setzt man in "Verborgene Seite 1" den Pluginaufruf mit `{{{expand 'pages = Unterseite 1,Unterseite 2,Unterseite 3'}}}` würde es gehen. Aber, klickt man auf den Titel einer "Unterseite ..." so schließt sich "Verborgene Seite 1".

**Comment by TN03** [comment]
Closed with https://github.com/TN03/expandcontract/commit/ec4354e27e6d07fd7b37cefa10e00e9912ec49aa
