### ISSUE TITLE
Welches CSS mit welchen Parametern als Standard in config.php?

### ISSUE THREAD

**Issue by TN03** [TN03/expandcontract#18]
Siehe https://github.com/TN03/expandcontract/commit/c853a0e0360b1c5d1dfbbff795fe246df029f58c

**Comment by frase-git** [comment]
Wie ich [hier](https://github.com/TN03/expandcontract/commit/c853a0e0360b1c5d1dfbbff795fe246df029f58c#commitcomment-69272849) bereits schrieb, wäre als Config-Default example1.css ohne Padding als Vorgabe in Ordnung.

Eigentlich sollte als Vorgabe überhapt nichts eingestellt sein - alle Schalter aus und alle Eingabefelder leer.
Das wäre komplett ohne Beeinflussung - der Anwender hat völlige Freiheit.
Aber, es wäre nicht besonders schön, wenn bei der Erstbenutzung "alles nackt" wäre.

Vorschlag, so, wie ich es in der Demo mit den Varianten gemacht habe:
`Inline buttons` - aus
`Stylesheet` - example1.css
`Padding` - leer
`First open` - aus
`Auto close` - an
`Show close button` - an
`Max-height` - leer

Damit wäre ein "vernünftiger" Start möglich.

**Comment by TN03** [comment]
Okay, ist dann hiermit https://github.com/TN03/expandcontract/commit/d56b33eb3ceec006f357aed8b738c76e23b99ef7 erledigt.
