### ISSUE TITLE
Parameter-Namen vereinheitlichen

### ISSUE THREAD

**Issue by frase-git** [TN03/expandcontract#19]
Aktuell heißen die (einige) Parameter:
`show-close`, `max-height`, `show-inline`, `content-padding`, `auto-close`
aber:
`firstopen`

Das sollte irgendwie vereinheitlicht werden.
Entweder alle mit Bindestrich: `first-open` oder alle ohne.

Ich neige dazu, alle ohne Bindestrich zu schreiben - das tippt sich schneller.
Mit Bindestrich ist es allerdings etwas übersichtlicher.

**Comment by TN03** [comment]
Wen wir hier, bzw. davor https://github.com/TN03/expandcontract/blob/ec4354e27e6d07fd7b37cefa10e00e9912ec49aa/index.php#L44 noch mittels str_replace() alle Bindestriche heraus filtern (und die paar Parameter dann im folgenden Code anpassen) kann man die Parameter mit / ohne Bindestrich und gemischt in Groß- / Kleinschreibung übergeben.
Wäre vielleicht auch eine Lösung?

**Comment by olape-git** [comment]
Ich wäre dann eher für first-open, es ist im Ganzen irgendwie besser zu lesen.
Wir können Holgers Idee doch aber umsetzen, man kann schon jetzt recht wild mit den Parametern umgehen, dann können wir die Wahl ob mit oder ohne Bindestrich auch noch dem Nutzer überlassen.

**Comment by frase-git** [comment]
> Wir können Holgers Idee doch aber umsetzen, man kann schon jetzt recht wild mit den Parametern umgehen, dann können wir die Wahl ob mit oder ohne Bindestrich auch noch dem Nutzer überlassen.

Tippfehler-tolerante Software die trotzdem richtig arbeitet - das kann nur gut sein!  ;-)
In der Plugin-Beschreibung würde ich dann aber alle nur mit BIndestrich erwähnen - das sieht in jedem Fall übersichtlicher aus.

**Comment by TN03** [comment]
Closed with https://github.com/TN03/expandcontract/pull/23
