### ISSUE TITLE
Hinweis, wenn keine Seiten gefunden werden

### ISSUE THREAD

**Issue by TN03** [TN03/expandcontract#21]
Werden vom Plugin keine Seiten gefunden, gibt es keine Meldung an den Admin. Es gibt einfach keine Ausgabe, was vielleicht verwirrend sein könnte.

**Comment by olape-git** [comment]
Damit man das Array nicht zweimal zählen muss, könnte man einfach ein else an dieses if anhängen https://github.com/TN03/expandcontract/blob/ec4354e27e6d07fd7b37cefa10e00e9912ec49aa/index.php#L150
Und eine Fehlermeldung auswerfen.

**Comment by TN03** [comment]
Closed with https://github.com/TN03/expandcontract/pull/23
