### ISSUE TITLE
Hinweis zur Codebereinigung

### ISSUE THREAD

**Issue by olape-git** [TN03/expandcontract#24]
Ich denke
https://github.com/TN03/expandcontract/blob/3ada24fd44c78d4d82700797a4fe9fa2f4dc9840/index.php#L94
hier kann das strtolower weg.
Das wird hier
https://github.com/TN03/expandcontract/blob/3ada24fd44c78d4d82700797a4fe9fa2f4dc9840/index.php#L88
schon mit erledigt.

**Comment by olape-git** [comment]
Ganz vergessen. Hier nochmal die Frage:
Ist es besser / übersichtlicher, die Hilfsfunktionen nach ecfuncs.php auszulagern?

**Comment by TN03** [comment]
> Ganz vergessen. Hier nochmal die Frage: Ist es besser / übersichtlicher, die Hilfsfunktionen nach ecfuncs.php auszulagern?

Das würde ja einen zusätzlichen Request bedeuten, den du bei den CSS-Dateien aber unbedingt vermeiden möchtest ;-).
Ernsthaft: nee, wozu dafür noch eine Datei. Ist doch so auch übersichtlich. Wenn, dann alles nach OOP übertragen.
BTW: was die Diskussion im Board wegen der CSS-Datei betrifft: der Request ist doch nicht soo schlimm, gegenüber dem Komfort, den es dem Nutzer und uns (für Beispiele), bringt. Klar könnte man alles zusammenfassen und auch später parsen, um einzelne "Examples" per DropDown anzubieten. Das ist dann aber doch alles "hintenrum durchs Knie" :).

**Comment by olape-git** [comment]
> Das würde ja einen zusätzlichen Request bedeuten, den du bei den CSS-Dateien aber unbedingt vermeiden möchtest ;-).

Den verstehe ich nicht. Wie sollte das include eine php-Datei einen zusätzlichen Request auslösen.

**Comment by olape-git** [comment]
> Klar könnte man alles zusammenfassen und auch später parsen, um einzelne "Examples" per DropDown anzubieten. Das ist dann aber doch alles "hintenrum durchs Knie" :).

So war das auch nicht gemeint.
Ich hätte nur Plugin-Stylesheet und den EINEN möglicherweise in der config gewählten zusätzlichen Style zusammengefasst. Das ganze also immer beim Speichern der config. Alles weitere erledigt dann XH wie immer.
