### ISSUE TITLE
Frage zu den möglichen Editoren

### ISSUE THREAD

**Issue by olape-git** [TN03/expandcontract#31]
Wir haben ja festgestellt, das Tiny, jedenfalls Version4, bei der Eingabe mehrere aufeinanderfolgender Leerzeichen nur ein „normales“ Leerzeichen schreibt und für den Rest irgendetwas anderes.
Machen das alle möglichen Editoren so?
Haben wir denn eigentlich aktuell noch andere Alternativen zu Tiny 4 und 5?

Wenn es nicht bei allen Editoren so ist, dann geht das Splitting mit explode per Leerzeichen an einigen Stellen in die Hose.

Dann sollten wir tatsächlich Christophs Vorschlag folgen und besser preg_split nutzen.
Das würden dann auch an einigen Stellen einen erneuten Durchlauf von cts, oder wie in meinem letzten Pull umbenannt: cleanTinySpaces, überflüssig machen

**Comment by TN03** [comment]
> Wenn es nicht bei allen Editoren so ist, dann geht das Splitting mit explode per Leerzeichen an einigen Stellen in die Hose.

Warum? Ich kann mir das , Stand aktueller Master, nicht richtig vorstellen.

**Comment by olape-git** [comment]
Du kannst das ja mal bei padding testen im Tiny mit mehreren Leerzeichen trennen sollte funktionieren, in der config mit mehreren Leerzeichen trennen wird nicht funktionieren. Weil dort sind es dann tatsächlich richtige einfache Leerzeichen.
Deswegen die Frage: Können wir uns darauf verlassen, dass das immer wie bei Tiny ist? Oder gehen wir besser auf Nummer sicher?

Auch dazu morgen eine mögliche Lösung.

**Comment by TN03** [comment]
Das muss ich nicht testen. Das einzige "Problem" war/ist, dass beim Tiny eben nicht "normale" Leerzeichen erzeugt werden und im aktuellen Code vor- und nach dem String Keine Leerzeichen stehen dürfen. Hier hatte str_replace() versagt, daher die RegExp in function ec_cts($data), die alle Leerzeichen vor- und nach $data sicher entfernt. Das klappt doch bisher problemlos.

Wenn in der Config.php für das Padding die Werte mit zu vielen Leerzeichen eingegeben werden, dann wird explode() zu viele Elemente erzeugen. Die entsprechen nicht der Vorgabe XXpx und erzeugt sogar einen Fehler mit Meldung an den User: da ist ein Problem in deiner Definition für das Padding. Gleiches gilt, wenn kein "px" angegeben ist - nue "0" ist okay. Alles abgedeckt IMHO. Dann braucht es *eigentlich* auch keinen Zähler, da der fünfte Wert ignoriert wird, falls der User 5 Werte im richtigen Format angibt. 

Das funktioniert doch, so wie es ist, alles richtig und gut. 
Ich verstehe jetzt, ehrlich gesagt, das Problem nicht. Auch eine Abhängigkeit vom Editor sehe ich (im aktuellen Master) nicht???

**Comment by TN03** [comment]
Closed with https://github.com/TN03/expandcontract/commit/7432fcb0faf453937d49a2698b5cdcc00ddd6ee1
