### ISSUE TITLE
Pages und Headlines

### ISSUE THREAD

**Issue by olape-git** [TN03/expandcontract#32]
Hat mal jemand versucht in Pages oder Headlines Wörter wie Onbord oder Office zu nutzen?
Also Wörter in denen On, ON, Off, OFF vorkommen.

Ich glaube nämlich fast,  aktuell geht das daneben.

**Comment by TN03** [comment]
Nee, nicht probiert. Meine Meinung on/off rauswerfen wo möglich. Besonders bei so Sachen wie Padding etc. Da finde ich sie total unüblich.

**Comment by olape-git** [comment]
> Meine Meinung on/off rauswerfen wo möglich. Besonders bei so Sachen wie Padding etc. Da finde ich sie total unüblich.

on off geht nicht ganz raus und ich persönlich finde es verständlicher als 1 oder 0.

Wenn das Problem aber tatsächlich besteht, gibt es morgen eine Lösung dazu.
Aber erst muss ich das mal testen.

**Comment by TN03** [comment]
> on off geht nicht ganz raus

Ja, das ist klar.


> und ich persönlich finde es verständlicher als 1 oder 0.
Die ganze digitale Welt besteht aus Nullen und Einsern ;-). 
Aber daran soll es jetzt nicht scheitern.

**Comment by TN03** [comment]
So, jetzt mal kurz probiert: `{{{expand('pages = off', 'headlines = on'}}}` . Funktioniert :)

**Comment by olape-git** [comment]
> So, jetzt mal kurz probiert: `{{{expand('pages = off', 'headlines = on'}}}` . Funktioniert :)

Das glaube ich.
Aber `{{{expand('pages = Office, Onboard', 'headlines = Offiziell Mist, Ontario'}}}`
funktioniert nicht.
