### ISSUE TITLE
Undefined offset

### ISSUE THREAD

**Issue by g7sim** [TN03/expandcontract#6]
NOTICE: Undefined offset: 1
I:\Xampp7410\inst\htdocs\x175\plugins\expandcontract\index.php:32

**Comment by frase-git** [comment]
This note only appears if the "old" plugin calls are still in there.
You can find the new ones here: https://github.com/TN03/expandcontract/pull/4#issuecomment-1072583616
or here: https://cmsimpleforum.com/viewtopic.php?f=16&p=83260#p83255

**Comment by g7sim** [comment]
It happend with the newest master of this site....php7.4
also : $cKey, $cValue are undefined
Final notice : make it complicated....

**Comment by TN03** [comment]
> NOTICE: Undefined offset: 1 I:\Xampp7410\inst\htdocs\x175\plugins\expandcontract\index.php:32

Yes. Should happen e.g. with {{{expand('')}}} or all given strings without a "=".
Arguments without containing a "="passed to the function will throw a notice (PHP 7.?) or a warning (on PHP 8). 

>Final notice : make it complicated....

Hehe, seems some people have too much free time this spring ;-)
